
package com.zhengtong.service.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ICService", targetNamespace = "http://ws.service.zhengtong.com/", wsdlLocation = "file:/C:/Users/fanyj/Desktop/ICService.xml")
public class ICService_Service
    extends Service
{

    private final static URL ICSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.zhengtong.service.ws.ICService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.zhengtong.service.ws.ICService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/fanyj/Desktop/ICService.xml");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/fanyj/Desktop/ICService.xml', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ICSERVICE_WSDL_LOCATION = url;
    }

    public ICService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ICService_Service() {
        super(ICSERVICE_WSDL_LOCATION, new QName("http://ws.service.zhengtong.com/", "ICService"));
    }

    /**
     * 
     * @return
     *     returns ICService
     */
    @WebEndpoint(name = "ICServicePort")
    public ICService getICServicePort() {
        return super.getPort(new QName("http://ws.service.zhengtong.com/", "ICServicePort"), ICService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICService
     */
    @WebEndpoint(name = "ICServicePort")
    public ICService getICServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service.zhengtong.com/", "ICServicePort"), ICService.class, features);
    }

}
