
package com.zhengtong.service.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICService", targetNamespace = "http://ws.service.zhengtong.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICService {


    /**
     * 
     * @param message
     * @return
     *     returns com.zhengtong.service.ws.IcResp
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "idCert", targetNamespace = "http://ws.service.zhengtong.com/", className = "com.zhengtong.service.ws.IdCert")
    @ResponseWrapper(localName = "idCertResponse", targetNamespace = "http://ws.service.zhengtong.com/", className = "com.zhengtong.service.ws.IdCertResponse")
    public IcResp idCert(
        @WebParam(name = "message", targetNamespace = "")
        Ic message);

    /**
     * 
     * @param message
     * @return
     *     returns com.zhengtong.service.ws.OcBizQResp
     */
    @WebMethod
    @WebResult(name = "message", targetNamespace = "")
    @RequestWrapper(localName = "orgCertBizQuery", targetNamespace = "http://ws.service.zhengtong.com/", className = "com.zhengtong.service.ws.OrgCertBizQuery")
    @ResponseWrapper(localName = "orgCertBizQueryResponse", targetNamespace = "http://ws.service.zhengtong.com/", className = "com.zhengtong.service.ws.OrgCertBizQueryResponse")
    public OcBizQResp orgCertBizQuery(
        @WebParam(name = "message", targetNamespace = "")
        OcBizQ message);

}
